from __future__ import annotations

PROVIDER_SIGNUP = {
    "BROWSER_USE_API_KEY": {
        "provider": "browser-use",
        "label": "Browser Use Cloud",
        "signup_url": "https://cloud.browser-use.com/",
        "docs_url": "https://docs.browser-use.com/",
        "env_var": "BROWSER_USE_API_KEY",
        "required_for": "Anti-bot cloud browser, profiles, recordings",
    },
    "BROWSERBASE_API_KEY": {
        "provider": "browserbase",
        "label": "Browserbase",
        "signup_url": "https://www.browserbase.com/",
        "docs_url": "https://docs.browserbase.com/",
        "env_var": "BROWSERBASE_API_KEY",
        "required_for": "Stagehand, hosted web agents, stealth sessions (docs-only until adapter ships)",
        "optional": True,
    },
    "HYPERBROWSER_API_KEY": {
        "provider": "hyperbrowser",
        "label": "Hyperbrowser",
        "signup_url": "https://www.hyperbrowser.ai/",
        "docs_url": "https://docs.hyperbrowser.ai/",
        "env_var": "HYPERBROWSER_API_KEY",
        "required_for": "Cloud scrape jobs and scale browser automation",
    },
    "AIRTOP_API_KEY": {
        "provider": "airtop",
        "label": "Airtop",
        "signup_url": "https://www.airtop.ai/",
        "docs_url": "https://docs.airtop.ai/",
        "env_var": "AIRTOP_API_KEY",
        "required_for": "Cloud sessions, page-query, scheduled GTM workflows",
    },
    "STEEL_API_KEY": {
        "provider": "steel",
        "label": "Steel",
        "signup_url": "https://steel.dev/",
        "docs_url": "https://docs.steel.dev/",
        "env_var": "STEEL_API_KEY",
        "required_for": "Hosted Chromium sessions over Playwright CDP",
    },
    "ORGO_API_KEY": {
        "provider": "orgo",
        "label": "Orgo",
        "signup_url": "https://orgo.ai/",
        "docs_url": "https://docs.orgo.ai/api-reference/introduction",
        "env_var": "ORGO_API_KEY",
        "required_for": "Full desktop / computer-use VMs",
    },
    "DECODO_PROXY": {
        "provider": "decodo-http",
        "label": "Decodo residential proxy",
        "signup_url": "https://decodo.com/",
        "docs_url": "https://decodo.com/proxies/residential-proxies",
        "env_var": "DECODO_PROXY",
        "required_for": "Optional residential proxy routing for raw HTTP (not required for direct HTTP)",
        "optional": True,
    },
    "BRIGHTDATA_API_KEY": {
        "provider": "brightdata-unlocker",
        "label": "Bright Data",
        "signup_url": "https://brightdata.com/",
        "docs_url": "https://docs.brightdata.com/api-reference/authentication",
        "env_var": "BRIGHTDATA_API_KEY",
        "required_for": "Web Unlocker, SERP API, and dataset extractors",
    },
    "BRIGHTDATA_UNLOCKER_ZONE": {
        "provider": "brightdata-unlocker",
        "label": "Bright Data Web Unlocker zone",
        "signup_url": "https://brightdata.com/cp/zones",
        "docs_url": "https://docs.brightdata.com/api-reference/rest-api/unlocker/unlock-website",
        "env_var": "BRIGHTDATA_UNLOCKER_ZONE",
        "required_for": "One-shot anti-bot URL unlock lane",
    },
    "BRIGHTDATA_SERP_ZONE": {
        "provider": "brightdata-serp",
        "label": "Bright Data SERP zone",
        "signup_url": "https://brightdata.com/cp/zones",
        "docs_url": "https://docs.brightdata.com/scraping-automation/serp-api/introduction",
        "env_var": "BRIGHTDATA_SERP_ZONE",
        "required_for": "Search engine results lane",
    },
    "BRIGHTDATA_BROWSER_USERNAME": {
        "provider": "brightdata-browser",
        "label": "Bright Data Scraping Browser username",
        "signup_url": "https://brightdata.com/cp/zones",
        "docs_url": "https://docs.brightdata.com/scraping-automation/scraping-browser/five-minute-how-to",
        "env_var": "BRIGHTDATA_BROWSER_USERNAME",
        "required_for": "Scraping Browser CDP lane",
    },
}
